FROM centos:7

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

RUN ls
RUN yum -y install epel-release

# python
# RUN yum -y install python3-pip python3 python3-devel python36-devel 

# X11 
RUN yum -y install xorg-x11-server-Xorg xorg-x11-xauth libX11-devel \
    libXpm-devel libXft-devel libXext-devel \
    libXt-devel

# OpenGL / x11vnc / fvwm 
RUN yum -y install mesa-libGL-devel mesa-dri-drivers x11vnc fvwm

# mpfr, gmp
RUN yum -y install mpfr-devel gmp-devel

# GIT, wget, cmake3
RUN yum -y install git wget cmake3

# Modern compilers 
RUN yum -y install centos-release-scl && \
    yum -y install devtoolset-7

# python
RUN yum -y install rh-python38-python-pip rh-python38-python-devel rh-python38-python

# misc useful
RUN yum -y install nano xterm

# CGAL
RUN wget https://github.com/CGAL/cgal/archive/refs/tags/v5.3.1.tar.gz && \
    tar zxf v5.3.1.tar.gz && \
    source scl_source enable devtoolset-7 && \
    mkdir build && \
    cd build && \
    cmake3 ../cgal-5.3.1 && \
    make && \
    make install && \
    cd ../ && \
    rm -rf build v5.3.1.tar.gz

# pyg4ometry deps 
RUN source scl_source enable rh-python38 && \
    pip install cython pybind11 auditwheel ipython distro
RUN yum -y install boost169-devel libjpeg-turbo-devel 

# pyg4ometry
ARG PYG4_TAG=5
RUN git clone https://stewartboogert@bitbucket.org/jairhul/pyg4ometry.git 

RUN cd pyg4ometry && \
    source scl_source enable devtoolset-7 && \
    source scl_source enable rh-python38 && \
    python setup.py build_ext --inplace && \
    pip install --editable . --user 

RUN echo "source scl_source enable devtoolset-7" >> /root/.bashrc && \
    echo "source scl_source enable rh-python38" >> /root/.bashrc && \
    echo "export MESA_GL_VERSION_OVERRIDE=3.2" >> /root/.bashrc && \
    echo "export MESA_GLSL_VERSION_OVERRIDE=150" >> /root/.bashrc
