FROM ubuntu:focal

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

CMD ["/bin/bash"]

WORKDIR /tmp

# start with more uptodate packages
RUN apt-get update

# build essentials 
RUN apt -y install build-essential

# python 
RUN apt-get -y install python3 python3-pip 

# required packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get -y install libxt-dev libglx-dev libgl1-mesa-dev wget libboost-all-dev emacs xvfb x11vnc fvwm

# vtk 
RUN wget https://www.vtk.org/files/release/9.0/vtk-9.0.0rc3-cp38-cp38-linux_x86_64.whl && \
    pip3 install vtk-9.0.0rc3-cp38-cp38-linux_x86_64.whl

# freecad
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install freecad && \
    ln -s /usr/lib/freecad/Mod /usr/lib/freecad-python3/&& \
    export PYTHONPATH=/usr/lib/freecad/lib/

# default python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# default pip
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# cython
RUN pip install cython

# ipython
RUN pip install ipython

# git
RUN apt-get -y install git

# pyg4ometry deps
RUN pip3 install pybind11
RUN apt-get -y install libcgal-dev
RUN pip3 install pandas distro

# pyg4ometry
RUN apt-get -y install libmpfr-dev libgmp-dev pybind11-dev
ARG PYG4_TAG=7
RUN git clone https://stewartboogert@bitbucket.org/jairhul/pyg4ometry.git && \
    cd pyg4ometry &&\
    git checkout CITests

RUN cd pyg4ometry && \
    python setup.py build_ext --inplace && \
    pip install --editable . --user 

