FROM ubuntu:focal

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

CMD ["/bin/bash"]

WORKDIR /tmp

# start with more uptodate packages
RUN apt-get update

# build essentials 
RUN apt -y install build-essential

# required packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata libxt-dev libglx-dev libgl1-mesa-dev \
    wget libboost-all-dev emacs xvfb x11vnc fvwm git libmpfr-dev libgmp-dev pybind11-dev \
    cmake libxi-dev libxmu-dev

# python 
RUN apt-get -y install python3 python3-pip && \
    pip3 install cython ipython pybind11 pandas distro

# vtk 
RUN wget https://www.vtk.org/files/release/9.0/vtk-9.0.0rc3-cp38-cp38-linux_x86_64.whl && \
    pip3 install vtk-9.0.0rc3-cp38-cp38-linux_x86_64.whl

# open cascade
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install occt* occt-misc

# open cascade from source
RUN git clone https://github.com/Open-Cascade-SAS/OCCT.git && \
    cd OCCT && git checkout V7_5_1 && cd ../ &&\
    mkdir OCCT-build && cd OCCT-build && \
    cmake ../OCCT &&\
    make -j4 &&\
    make install &&\
    cd ../

# CGAL
RUN git clone https://github.com/CGAL/cgal.git && \
    cd cgal && git checkout v5.4.1 && cd ../ && \
    mkdir cgal-build && cd cgal-build && cmake ../cgal && make install 

# default python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# pyg4ometry
ARG PYG4_TAG=1
RUN git clone https://stewartboogert@bitbucket.org/jairhul/pyg4ometry.git && \
    cd pyg4ometry &&\
    git checkout develop &&\
    patch -R /usr/local/include/opencascade/TDocStd_Application.hxx < docker/patches/TDocStd_Application.patch    

RUN cd pyg4ometry && \
    pip install --editable . 

RUN apt install -y patchelf && \
    pip install auditwheel twine

# Stuff for packaging on pypi (remember already have py3.8)
RUN apt install -y software-properties-common curl &&\
    add-apt-repository -y ppa:deadsnakes/ppa &&\
    apt update &&\
    apt install -y python3.7-dev python3.9-dev python3.10-dev python3.11-dev &&\
    apt install -y python3.7-distutils python3.9-distutils python3.10-distutils python3.11-distutils &&\
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 &&\
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 &&\
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9 &&\
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.7 &&\
    python3.11 -m pip install cython &&\
    python3.10 -m pip install cython &&\
    python3.9 -m pip install cython &&\
    python3.7 -m pip install cython 

#RUN cd pyg4ometry && \
#    python3.7 setup.py bdist_wheel && \
#    python setup.py bdist_wheel && \
#    python3.9 setup.py bdist_wheel && \
#    python3.10 setup.py bdist_wheel && \
#    python3.11 setup.py bdist_wheel && \
#    auditwheel repair dist/*whl -w dist/ --plat manylinux_2_31_x86_64